import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {createDocument,element,textNode,DocumentStore,find} from '../dist/core/model.js';
import {serializeHtml} from '../dist/core/html.js';
import {tokenizeHtmlStateSelector,listHtmlStates,createHtmlState,bindHtmlState,setHtmlStateProperties,recordHtmlStateProperties,removeHtmlState,getHtmlTransitions,setHtmlTransitions,getHtmlStateTransitions,setHtmlStateTransitions,exportHtmlStateCss,exportHtmlStateRuntime,bindHtmlStateInteraction,listHtmlStateInteractions,removeHtmlStateInteraction,HtmlStatePreview} from '../dist/core/html-states.js';
function fixture(css='',inline=''){const node=element('button',{id:'card',style:inline}),trigger=element('button',{id:'trigger'}),style=element('style',{},[textNode(css)]),doc=createDocument(element('html',{},[element('head',{},[style]),element('body',{},[node,trigger])]),'HTML','states.html');return {doc,node,trigger,style};}
const source=n=>n.children.map(c=>c.text||'').join('');
const state=doc=>listHtmlStates(doc).states[0];
function native(options={}){const attrs=new Map(Object.entries(options.attrs||{}));return {nodeType:1,parentElement:null,textContent:options.textContent||'',sheet:options.sheet||{disabled:false},getAttribute:name=>attrs.has(name)?attrs.get(name):null,setAttribute:(name,value)=>attrs.set(name,String(value)),removeAttribute:name=>attrs.delete(name),hasAttribute:name=>attrs.has(name),getBoundingClientRect:()=>({width:100}),matches:()=>true,...options};}
function previewFixture(css){const button=native(),parent=native(),style=native({textContent:css}),freeze=native({attrs:{'data-xamora-design-transitions':''}});button.parentElement=parent;const document={querySelectorAll:selector=>selector==='style'?[style,freeze]:selector==='style[data-xamora-design-transitions]'?[freeze]:[],documentElement:native()};return {button,parent,style,freeze,document,elements:new Map([['card',button]])};}

test('selector lexer recognizes pseudo tokens without touching attribute strings/comments/escaped identifiers',()=>{const tokens=tokenizeHtmlStateSelector('[data-label=":hover"] .escaped\\:hover:hover:not(:disabled) /* :active */');assert.deepEqual(tokens.filter(t=>t.kind==='pseudo').map(t=>t.name),['hover','not','disabled']);assert.equal(tokens.find(t=>t.kind==='class').name,'escaped:hover');assert.equal(tokens[0].value,':hover');});
test('imported states retain grouping conditions and source-backed values',()=>{const f=fixture('/* preserve */ @media (width > 400px) { @layer controls { .card:hover { opacity:.4; color:red; } } } .is-open { display:block; } [data-state="expanded"] {height:200px;}');const states=listHtmlStates(f.doc).states;assert.equal(states.length,3);assert.equal(states[0].kind,'hover');assert.deepEqual(states[0].conditions,['@media (width > 400px)','@layer controls']);assert.equal(states[0].values.opacity,'.4');assert.equal(states[1].kind,'class');assert.equal(states[2].kind,'data');});
test('editing imported declarations preserves comments and unrelated source byte-for-byte',()=>{const before='/* before */ .card:hover { /* keep */ color:red; opacity:.4; } @supports(display:grid) {.other {display:grid}}',f=fixture(before);setHtmlStateProperties(f.doc,state(f.doc).id,{color:'blue'});assert.ok(source(f.style).startsWith('/* before */ '));assert.ok(source(f.style).endsWith(' @supports(display:grid) {.other {display:grid}}'));assert.match(source(f.style),/\/\* keep \*\//);assert.equal(state(f.doc).values.opacity,'.4');assert.equal(state(f.doc).values.color,'blue');});
test('source edits are rediscovered without hidden metadata',()=>{const f=fixture('.card:hover {color:red;}'),id=state(f.doc).id;f.style.children[0].text='.card:hover {color:green;opacity:.5;}';assert.equal(state(f.doc).id,id);assert.equal(state(f.doc).values.color,'green');assert.equal(state(f.doc).values.opacity,'.5');});
test('create and bind authored native/class/data/named states use ordinary CSS and source attributes',()=>{const f=fixture();for(const kind of ['hover','focus-visible','active','disabled','checked','class','data','named']){const created=createHtmlState(f.doc,f.node.id,{kind,name:'expanded',values:{opacity:'.8'}});assert.equal(created.kind,kind);assert.ok(created.targetIds.includes(f.node.id));assert.ok(created.binding);assert.match(serializeHtml(f.doc),/data-xamora-target/);bindHtmlState(f.doc,created.id,f.trigger.id);assert.ok(listHtmlStates(f.doc).states.find(s=>s.id===created.id).targetIds.includes(f.trigger.id));}assert.equal(f.node.props['data-xamora-state'],undefined);assert.equal(f.node.props.class,undefined);});
test('recording promotes inline conflicts explicitly while retaining original base source bytes',()=>{const f=fixture('', 'opacity:1; margin:10px; color:red;'),before=f.node.props.style,created=createHtmlState(f.doc,f.node.id,{kind:'hover',values:{opacity:'.4'}});assert.equal(created.values.opacity,'.4 !important');recordHtmlStateProperties(f.doc,created.id,f.node.id,{'margin-left':'20px',scale:'1.1'});const next=state(f.doc);assert.equal(next.values['margin-left'],'20px !important');assert.equal(next.values.scale,'1.1');assert.equal(f.node.props.style,before);});
test('recording shared state accounts for inline conflicts on every bound target',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded'});f.trigger.props.style='opacity:1;';bindHtmlState(f.doc,created.id,f.trigger.id);recordHtmlStateProperties(f.doc,created.id,f.node.id,{opacity:'.5'});assert.equal(state(f.doc).values.opacity,'.5 !important');});
test('state mutation and repeat recording are undoable and no-op safe',()=>{const f=fixture('', 'opacity:1;'),store=new DocumentStore(f.doc);let created;store.transaction('Create state',doc=>created=createHtmlState(doc,f.node.id,{kind:'hover'}));store.transaction('Record',doc=>recordHtmlStateProperties(doc,created.id,f.node.id,{opacity:'.4'}));const textId=find(store.document.root,created.styleId).children[0].id;store.transaction('Record',doc=>recordHtmlStateProperties(doc,created.id,f.node.id,{opacity:'.4'}));assert.equal(store.history.length,2);assert.equal(find(store.document.root,created.styleId).children[0].id,textId);store.undo();assert.equal(state(store.document).values.opacity,undefined);assert.equal(find(store.document.root,f.node.id).props.style,'opacity:1;');store.redo();assert.equal(state(store.document).values.opacity,'.4 !important');});
test('deleting declarations and state rules leaves surrounding rules intact',()=>{const f=fixture('.card:hover {color:red;opacity:.4;} .other {padding:1px;}'),id=state(f.doc).id;setHtmlStateProperties(f.doc,id,{color:null});assert.equal(state(f.doc).values.color,undefined);removeHtmlState(f.doc,id);assert.equal(listHtmlStates(f.doc).states.length,0);assert.match(source(f.style),/\.other \{padding:1px;\}/);});
test('transition shorthand imports separate functions, negative delays and allow-discrete',()=>{const f=fixture('', 'transition: opacity .4s ease -.1s, display 1s steps(3, end) allow-discrete;');const items=getHtmlTransitions(f.doc,f.node.id);assert.deepEqual(items,[{property:'opacity',duration:400,delay:-100,easing:'ease',behavior:'normal'},{property:'display',duration:1000,delay:0,easing:'steps(3, end)',behavior:'allow-discrete'}]);});
test('longhand transition timing lists preceding properties repeat according to CSS rules',()=>{const f=fixture('', 'transition-duration:100ms,200ms;transition-delay:-.1s;transition-property:opacity,scale,color;');const list=getHtmlTransitions(f.doc,f.node.id);assert.deepEqual(list.map(i=>i.duration),[100,200,100]);assert.deepEqual(list.map(i=>i.delay),[-100,-100,-100]);});
test('transition edits preserve unrelated inline declarations and important priority',()=>{const f=fixture('', 'color:red;transition-duration:2s !important;transition:opacity 1s ease;');assert.equal(getHtmlTransitions(f.doc,f.node.id)[0].duration,2000);setHtmlTransitions(f.doc,f.node.id,[{property:'opacity',duration:450,delay:-30,easing:'linear',behavior:'normal'}]);assert.match(f.node.props.style,/color:red/);assert.match(f.node.props.style,/transition-duration: 450ms !important/);assert.equal(getHtmlTransitions(f.doc,f.node.id)[0].duration,450);});
test('repeated transition edit does not add history or reformat source again',()=>{const f=fixture(),store=new DocumentStore(f.doc),items=[{property:'opacity',duration:200,delay:0,easing:'ease',behavior:'normal'}];store.transaction('Transition',doc=>setHtmlTransitions(doc,f.node.id,items));const before=serializeHtml(store.document);store.transaction('Transition',doc=>setHtmlTransitions(doc,f.node.id,items));assert.equal(store.history.length,1);assert.equal(serializeHtml(store.document),before);});
test('state transitions are ordinary CSS declarations editable independently of base',()=>{const f=fixture('', 'transition:opacity .2s;'),created=createHtmlState(f.doc,f.node.id,{kind:'hover'});setHtmlStateTransitions(f.doc,created.id,[{property:'opacity',duration:900,delay:100,easing:'ease-in',behavior:'normal'}]);assert.equal(getHtmlStateTransitions(f.doc,created.id)[0].duration,900);assert.equal(getHtmlTransitions(f.doc,f.node.id)[0].duration,200);});
test('computed transitions ignore the designer freeze sheet and restore it afterwards',()=>{const f=fixture(),freeze={sheet:{disabled:false}},nativeNode=native();nativeNode.ownerDocument={querySelectorAll:()=>[freeze],defaultView:{getComputedStyle:()=>({getPropertyValue:key=>({'transition-property':freeze.sheet.disabled?'opacity':'none','transition-duration':freeze.sheet.disabled?'.4s':'0s','transition-delay':'0s','transition-timing-function':'ease','transition-behavior':'normal'}[key]||'')})}};const list=getHtmlTransitions(f.doc,f.node.id,{elements:new Map([[f.node.id,nativeNode]])});assert.equal(list[0].property,'opacity');assert.equal(list[0].duration,400);assert.equal(freeze.sheet.disabled,false);});
test('unresolved transition variables fail safely while live computed values remain usable',()=>{const f=fixture('', 'transition:var(--motion);');assert.throws(()=>getHtmlTransitions(f.doc,f.node.id),/resolved design preview/);const nativeNode=native({attrs:{style:f.node.props.style}});nativeNode.ownerDocument={defaultView:{getComputedStyle:()=>({getPropertyValue:key=>({'transition-property':'opacity','transition-duration':'1s'}[key]||'')})}};assert.equal(getHtmlTransitions(f.doc,f.node.id,{elements:new Map([[f.node.id,nativeNode]])})[0].duration,1000);});
test('interaction binding is idempotent, preserves existing event handlers and is source-visible',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded'});f.trigger.props.onclick='console.log("existing")';const store=new DocumentStore(f.doc);let binding;store.transaction('Bind',doc=>binding=bindHtmlStateInteraction(doc,created.id,{triggerNodeId:f.trigger.id,event:'click',action:'toggle'}));store.transaction('Bind',doc=>bindHtmlStateInteraction(doc,created.id,{triggerNodeId:f.trigger.id,event:'click',action:'toggle'}));assert.equal(store.history.length,1);assert.equal(listHtmlStateInteractions(store.document).length,1);assert.equal(find(store.document.root,f.trigger.id).props.onclick,'console.log("existing")');assert.match(serializeHtml(store.document),/data-xamora-state-actions/);assert.match(serializeHtml(store.document),/data-xamora-state-runtime/);removeHtmlStateInteraction(store.document,binding.id);assert.equal(listHtmlStateInteractions(store.document).length,0);assert.doesNotMatch(serializeHtml(store.document),/data-xamora-state-runtime/);});
test('interaction event supports independent click/change/enter/leave without duplicate target events',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded'});for(const event of ['click','change','pointerenter','pointerleave'])bindHtmlStateInteraction(f.doc,created.id,{triggerNodeId:f.trigger.id,event,action:'set'});bindHtmlStateInteraction(f.doc,created.id,{triggerNodeId:f.trigger.id,event:'click',action:'clear'});const bindings=listHtmlStateInteractions(f.doc);assert.equal(bindings.length,4);assert.equal(bindings.find(b=>b.event==='click').action,'clear');});
test('exported runtime toggles native data state and honors non-bubbling pointer targets',()=>{const listeners=new Map(),target=native({attrs:{'data-xamora-target':'state-target-1'}}),trigger=native({attrs:{'data-xamora-state-actions':JSON.stringify([{name:'expanded',target:'state-target-1',event:'click',action:'toggle'},{name:'expanded',target:'state-target-1',event:'pointerenter',action:'set'}])}});trigger.closest=()=>trigger;const document={addEventListener:(event,handler,capture)=>listeners.set(event,{handler,capture}),querySelectorAll:()=>[target]};vm.runInNewContext(exportHtmlStateRuntime(),{document});listeners.get('click').handler({target:trigger});assert.equal(target.getAttribute('data-xamora-state'),'expanded');listeners.get('click').handler({target:trigger});assert.equal(target.getAttribute('data-xamora-state'),null);assert.equal(listeners.get('pointerenter').capture,true);listeners.get('pointerenter').handler({target:{closest:()=>trigger}});assert.equal(target.getAttribute('data-xamora-state'),null);listeners.get('pointerenter').handler({target:trigger});assert.equal(target.getAttribute('data-xamora-state'),'expanded');});
test('pseudo preview rewrites only selector tokens in original rule positions and restores exact cascade source',()=>{const css='/*before*/ @media (width>10px){.card:hover {color:red;}} .card.is-open {color:blue;} [title=":hover"]{opacity:.3}',f=previewFixture(css),preview=new HtmlStatePreview(f);preview.setState({kind:'hover',selector:'.card:hover',values:{color:'red'},conditions:[]},'card');assert.ok(f.style.textContent.indexOf('color:red')<f.style.textContent.indexOf('color:blue'));assert.match(f.style.textContent,/\[title=":hover"\]/);assert.match(f.style.textContent,/@media/);assert.match(f.style.textContent,/data-xamora-preview-state/);assert.ok(f.parent.getAttribute('data-xamora-preview-state'));preview.clear();assert.equal(f.style.textContent,css);assert.equal(f.button.getAttribute('data-xamora-preview-state'),null);assert.equal(f.parent.getAttribute('data-xamora-preview-state'),null);});
test('named/class/data preview restores original attributes and transition freeze state',()=>{const f=previewFixture(''),preview=new HtmlStatePreview(f);f.button.setAttribute('class','base');f.button.setAttribute('data-xamora-state','existing');preview.setState({kind:'named',name:'expanded'},'card',{transitions:true});assert.equal(f.button.getAttribute('data-xamora-state'),'existing expanded');assert.equal(f.freeze.sheet.disabled,true);preview.clear();assert.equal(f.button.getAttribute('data-xamora-state'),'existing');assert.equal(f.freeze.sheet.disabled,false);preview.setState({kind:'class',name:'selected'},'card');assert.equal(f.button.getAttribute('class'),'base selected');preview.setState({kind:'data',attribute:'data-state',value:'open'},'card');assert.equal(f.button.getAttribute('class'),'base');assert.equal(f.button.getAttribute('data-state'),'open');preview.dispose();assert.equal(f.button.getAttribute('data-state'),null);});
test('CSS export preserves imports, state and non-state rules together',()=>{const css='@import "theme.css"; @layer states {.card:hover {color:red}} .base{color:blue}',f=fixture(css);assert.equal(exportHtmlStateCss(f.doc),css);});
test('invalid state declarations, interaction configs and timing are rejected without injection',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'hover'});for(const value of ['red;color:blue','</style><script>x</script>','calc(1px'])assert.throws(()=>setHtmlStateProperties(f.doc,created.id,{color:value}));assert.throws(()=>setHtmlTransitions(f.doc,f.node.id,[{property:'opacity',duration:-1}]));assert.throws(()=>bindHtmlStateInteraction(f.doc,created.id,{triggerNodeId:f.trigger.id}));assert.throws(()=>createHtmlState(f.doc,f.node.id,{kind:'data',name:'ok',attribute:'onclick'}));});
test('inline important bases report a conflict before mutation instead of exporting ineffective state CSS',()=>{const f=fixture('', 'opacity:1 !important;'),before=serializeHtml(f.doc);assert.throws(()=>createHtmlState(f.doc,f.node.id,{kind:'hover',values:{opacity:'.4'}}),/inline opacity base value is !important/);assert.equal(serializeHtml(f.doc),before);});
test('imported important stylesheet transitions get an explicit inline override when edited',()=>{const f=fixture('.card{transition-duration:2s !important;}'),nativeNode=native();nativeNode.ownerDocument={defaultView:{getComputedStyle:()=>({getPropertyValue:key=>({'transition-property':'opacity','transition-duration':'2s'}[key]||'')})}};setHtmlTransitions(f.doc,f.node.id,[{property:'opacity',duration:300}],{elements:new Map([[f.node.id,nativeNode]])});assert.match(f.node.props.style,/transition-duration: 300ms !important/);});
test('named state runtime supports focus/input/double-click events explicitly',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded'});for(const event of ['focusin','focusout','input','dblclick'])bindHtmlStateInteraction(f.doc,created.id,{triggerNodeId:f.trigger.id,event,action:'set'});assert.equal(listHtmlStateInteractions(f.doc).length,4);assert.match(exportHtmlStateRuntime(),/'focusin'/);});
test('compound pseudo preview propagates hover but keeps disabled state on the selected control',()=>{const f=previewFixture('.parent:hover .card:disabled {opacity:.4;} .parent:disabled {color:red;}'),preview=new HtmlStatePreview(f);f.button.disabled=false;preview.setState({kind:'hover',selector:'.parent:hover .card:disabled'},'card');assert.match(f.button.getAttribute('data-xamora-preview-state'),/-disabled/);assert.doesNotMatch(f.parent.getAttribute('data-xamora-preview-state'),/-disabled/);assert.match(f.parent.getAttribute('data-xamora-preview-state'),/-hover/);assert.equal(f.button.disabled,true);preview.clear();assert.equal(f.button.disabled,false);});
test('focus-visible preview includes focus and ancestor focus-within state styling',()=>{const f=previewFixture('.card:focus-visible{color:red}.card:focus{opacity:.8}.parent:focus-within{scale:1.1}'),preview=new HtmlStatePreview(f);preview.setState({kind:'focus-visible',selector:'.card:focus-visible'},'card');assert.match(f.style.textContent,/-focus-within/);assert.match(f.button.getAttribute('data-xamora-preview-state'),/-focus-visible/);assert.match(f.parent.getAttribute('data-xamora-preview-state'),/-focus-within/);assert.doesNotMatch(f.parent.getAttribute('data-xamora-preview-state'),/-focus-visible/);preview.clear();});
test('deleting the last named state removes only its actions and shared runtime when unused, with one undo',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded',values:{opacity:'.5'}});f.trigger.props.onclick='existingHandler()';bindHtmlStateInteraction(f.doc,created.id,{triggerNodeId:f.trigger.id,event:'click',action:'toggle'});const store=new DocumentStore(f.doc),before=serializeHtml(store.document);store.transaction('Delete state',doc=>removeHtmlState(doc,created.id));assert.equal(listHtmlStateInteractions(store.document).length,0);assert.equal(find(store.document.root,f.trigger.id).props.onclick,'existingHandler()');assert.doesNotMatch(serializeHtml(store.document),/data-xamora-state-runtime/);assert.equal(store.history.length,1);store.undo();assert.equal(serializeHtml(store.document),before);assert.equal(listHtmlStateInteractions(store.document).length,1);store.redo();assert.equal(listHtmlStateInteractions(store.document).length,0);});
test('deleting one of several named rules preserves its action until the last rule is removed',()=>{const f=fixture(),created=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded',values:{color:'red'}});bindHtmlStateInteraction(f.doc,created.id,{triggerNodeId:f.trigger.id});const authored=find(f.doc.root,created.styleId);authored.children[0].text+='\n'+created.selector+' .detail { opacity:.5; }\n';const matching=()=>listHtmlStates(f.doc).states.filter(s=>s.kind==='named'&&s.binding===created.binding&&s.name===created.name);assert.equal(matching().length,2);removeHtmlState(f.doc,created.id);assert.equal(listHtmlStateInteractions(f.doc).length,1);assert.match(serializeHtml(f.doc),/data-xamora-state-runtime/);removeHtmlState(f.doc,matching()[0].id);assert.equal(listHtmlStateInteractions(f.doc).length,0);assert.doesNotMatch(serializeHtml(f.doc),/data-xamora-state-runtime/);});
test('named state deletion preserves other state actions, existing handlers and malformed unrelated JSON',()=>{const f=fixture(),first=createHtmlState(f.doc,f.node.id,{kind:'named',name:'expanded'}),second=createHtmlState(f.doc,f.node.id,{kind:'named',name:'selected'});bindHtmlStateInteraction(f.doc,first.id,{triggerNodeId:f.trigger.id});bindHtmlStateInteraction(f.doc,second.id,{triggerNodeId:f.trigger.id});f.node.props['data-xamora-state-actions']='{malformed';removeHtmlState(f.doc,first.id);const actions=JSON.parse(f.trigger.props['data-xamora-state-actions']);assert.equal(actions.length,1);assert.equal(actions[0].name,'selected');assert.equal(f.node.props['data-xamora-state-actions'],'{malformed');removeHtmlState(f.doc,second.id);assert.equal(f.trigger.props['data-xamora-state-actions'],undefined);assert.equal(f.node.props['data-xamora-state-actions'],'{malformed');assert.match(serializeHtml(f.doc),/data-xamora-state-runtime/);});
