import test from 'node:test';
import assert from 'node:assert/strict';
import {createDocument,element,find,clone} from '../dist/core/model.js';
import {parseXaml} from '../dist/core/xaml.js';
import {resourceEntries,findResource,selectStyles,resolveStyle,ensureDesignNamespace} from '../dist/core/styling.js';
import {transformMatrix,brushCSS,applyAppearance,designProperties,isDesignElement,sampleDesignData} from '../dist/core/appearance.js';
import {parsePath,serializePath,pathPoints,movePathPoint,shapeToPath} from '../dist/core/vector.js';
import {motionDocument,motionBase,captureMotion,restoreMotion,patchMotion} from '../dist/core/motion-render.js';
import {installDOM,FakeElement} from './dom-fixture.mjs';
installDOM();
const X='xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"';

test('merged resources use last merge then primary dictionary precedence',()=>{
  const doc=parseXaml(`<Grid ${X}><Grid.Resources><ResourceDictionary><ResourceDictionary.MergedDictionaries><ResourceDictionary><SolidColorBrush x:Key="Accent" Color="Red"/></ResourceDictionary><ResourceDictionary><SolidColorBrush x:Key="Accent" Color="Blue"/></ResourceDictionary></ResourceDictionary.MergedDictionaries><SolidColorBrush x:Key="Accent" Color="Green"/></ResourceDictionary></Grid.Resources><Border/></Grid>`),target=doc.root.children.at(-1);
  assert.deepEqual(resourceEntries(doc.root).map(n=>n.props.Color),['Red','Blue','Green']);assert.equal(findResource(doc,target,'Accent').props.Color,'Green');
  doc.root.children[0].children[0].children.pop();assert.equal(findResource(doc,target,'Accent').props.Color,'Blue');
});
test('resource Source cycles terminate without hiding primary entries',()=>{const dictionary=element('ResourceDictionary',{Source:'a'},[element('SolidColorBrush',{'x:Key':'B',Color:'Blue'})]),doc=createDocument(dictionary);let calls=0;assert.equal(findResource(doc,dictionary,'B',()=>{calls++;return doc;}).props.Color,'Blue');assert.equal(calls,1);});
test('nearest implicit style replaces an ancestor implicit style',()=>{const doc=parseXaml(`<Grid><Grid.Resources><Style TargetType="Button"><Setter Property="Width" Value="90"/></Style></Grid.Resources><StackPanel><StackPanel.Resources><Style TargetType="Button"><Setter Property="Height" Value="40"/></Style></StackPanel.Resources><Button/></StackPanel></Grid>`),button=doc.root.children[1].children[1],result=resolveStyle(doc,button);assert.equal(selectStyles(doc,button).length,1);assert.equal(result.properties.Height,'40');assert.equal(result.properties.Width,undefined);});
test('explicit style inherits BasedOn and local properties win trigger values',()=>{const doc=parseXaml(`<Grid ${X}><Grid.Resources><Style x:Key="Base"><Setter Property="Width" Value="90"/></Style><Style x:Key="Accent" BasedOn="{StaticResource Base}"><Setter Property="Opacity" Value="0.8"/><Style.Triggers><Trigger Property="IsMouseOver" Value="True"><Setter Property="Opacity" Value="0.5"/></Trigger></Style.Triggers></Style></Grid.Resources><Button Style="{StaticResource Accent}" Opacity="0.9"/></Grid>`),button=doc.root.children[1],result=resolveStyle(doc,button,{transient:{IsMouseOver:true}});assert.equal(result.properties.Width,'90');assert.equal(result.properties.Opacity,'0.9');assert.equal(result.active.length,1);});
test('MultiDataTrigger requires every condition and records activation',()=>{const doc=parseXaml(`<Button><Button.Style><Style><Style.Triggers><MultiDataTrigger><MultiDataTrigger.Conditions><Condition Binding="{Binding IsReady}" Value="True"/><Condition Binding="{Binding Count}" Value="3"/></MultiDataTrigger.Conditions><Setter Property="Opacity" Value="0.5"/></MultiDataTrigger></Style.Triggers></Style></Button.Style></Button>`);assert.equal(resolveStyle(doc,doc.root,{context:{IsReady:true,Count:3}}).properties.Opacity,'0.5');assert.equal(resolveStyle(doc,doc.root,{context:{IsReady:false,Count:3}}).active.length,0);});
test('object setters clone their objects and local property elements take precedence',()=>{const doc=parseXaml(`<Button><Button.Style><Style><Setter Property="Background"><Setter.Value><SolidColorBrush Color="Blue"/></Setter.Value></Setter></Style></Button.Style></Button>`),before=JSON.stringify(doc),effective=resolveStyle(doc,doc.root).node;const brush=effective.children.find(c=>c.type==='Button.Background').children[0];brush.props.Color='Red';assert.equal(JSON.stringify(doc),before);doc.root.children.push(element('Button.Background',{},[element('SolidColorBrush',{Color:'Green'})]));assert.equal(resolveStyle(doc,doc.root).node.children.filter(c=>c.type==='Button.Background').length,1);});
test('null local Style suppresses implicit style',()=>{const doc=parseXaml(`<Grid><Grid.Resources><Style TargetType="Button"><Setter Property="Opacity" Value="0.5"/></Style></Grid.Resources><Button Style="{x:Null}"/></Grid>`);assert.deepEqual(selectStyles(doc,doc.root.children[1]),[]);});
test('transform groups preserve order and rotation center',()=>{const group=element('TransformGroup',{},[element('TranslateTransform',{X:'10'}),element('RotateTransform',{Angle:'90'})]),matrix=transformMatrix(group);assert.ok(Math.abs(matrix[4])<1e-10);assert.ok(Math.abs(matrix[5]-10)<1e-10);const centered=transformMatrix(element('ScaleTransform',{ScaleX:'2',ScaleY:'3',CenterX:'5',CenterY:'7'}));assert.deepEqual(centered,[2,0,0,3,-5,-14]);});
test('appearance keeps plugin transforms and keeps Canvas coordinates parent-owned',()=>{const doc=createDocument(element('Button',{'Canvas.Left':'42',Opacity:'0'})),el=new FakeElement();el.style.transform='rotate(12deg)';el.style.left='5px';applyAppearance(el,doc.root,doc);assert.equal(el.style.transform,'rotate(12deg)');assert.equal(el.style.left,'5px');assert.equal(el.style.opacity,'0');});
test('collapsed appearance restores the original layout display',()=>{const doc=createDocument(element('Grid',{Visibility:'Collapsed'})),el=new FakeElement();el.style.display='grid';applyAppearance(el,doc.root,doc);assert.equal(el.style.display,'none');doc.root.props.Visibility='Visible';applyAppearance(el,doc.root,doc);assert.equal(el.style.display,'grid');});
test('gradient stops are sorted and ARGB colors become CSS colors',()=>{const brush=element('LinearGradientBrush',{StartPoint:'0,0',EndPoint:'1,0'},[element('GradientStop',{Offset:'1',Color:'#80FF0000'}),element('GradientStop',{Offset:'0',Color:'Blue'})]);assert.equal(brushCSS(brush),'linear-gradient(90deg,Blue 0%,#FF000080 100%)');});
test('design-only attributes use namespace identity, including alternate prefixes',()=>{const doc=parseXaml('<Grid xmlns:d="urn:custom" xmlns:design="http://schemas.microsoft.com/expression/blend/2008" d:Text="Runtime custom" design:Width="120"><design:Button/><d:Button/></Grid>');assert.deepEqual(designProperties(doc.root,doc),{Width:'120'});assert.equal(isDesignElement(doc.root.children[0],doc),true);assert.equal(isDesignElement(doc.root.children[1],doc),false);const prefix=ensureDesignNamespace(doc);assert.equal(prefix,'design');assert.match(doc.root.props['mc:Ignorable'],/design/);assert.equal(doc.root.props['xmlns:d'],'urn:custom');});
test('design sample values infer nested fields without prototype writes',()=>{const node=element('TextBlock',{Text:'{Binding Person.Name}',Tag:'{Binding __proto__.polluted}'}),rows=sampleDesignData(node,2);assert.equal(rows[1].Person.Name,'Name 2');assert.equal({}.polluted,undefined);});
test('path parser normalizes relative moves and smooth controls',()=>{const commands=parsePath('m 10,20 5,5 c 1,2 3,4 5,6 s 4,5 8,9 z');assert.deepEqual(commands[1],{type:'L',values:[15,25]});assert.deepEqual(commands[3],{type:'C',values:[22,33,24,36,28,40]});assert.equal(parsePath(serializePath(commands)).length,5);});
test('moving a Bezier handle changes only that handle',()=>{const commands=parsePath('M 0,0 C 10,0 20,10 30,10'),points=pathPoints(commands),moved=movePathPoint(commands,points[1],5,7);assert.equal(points[1].control,true);assert.deepEqual(moved[1].values,[5,7,20,10,30,10]);assert.deepEqual(commands[1].values,[10,0,20,10,30,10]);});
test('path parsing rejects incomplete commands and invalid arc flags',()=>{assert.throws(()=>parsePath('M 0,0 C 1,2'));assert.throws(()=>parsePath('M 0,0 A 1,2,0,2,1,10,20'));assert.throws(()=>parsePath('M 0,0 <script>'));});
test('shape conversion preserves ellipse and rounded rectangle geometry',()=>{assert.equal(parsePath(shapeToPath(element('Ellipse',{Width:'80',Height:'40'}))).filter(c=>c.type==='A').length,2);assert.equal(parsePath(shapeToPath(element('Rectangle',{Width:'80',Height:'40',RadiusX:'8',RadiusY:'4'}))).filter(c=>c.type==='A').length,4);});
function rendererFor(doc){const elements=new Map();for(const node of [doc.root,...doc.root.children.filter(n=>n.kind==='element'&&!n.type.includes('.'))]){const el=new FakeElement();el.textContent=node.props.Text||node.props.Content||'';elements.set(node.id,el);}return {document:doc,elements,sampleData:{},contextFor:()=>({}),runtimeTemplates:[],templateOwners:new Map()};}
test('motion document includes runtime template instances without changing source',()=>{const doc=createDocument(element('Button',{Content:'Hello'})),renderer=rendererFor(doc),tree=element('Border');renderer.runtimeTemplates=[{ownerId:doc.root.id,tree}];assert.equal(find(motionDocument(renderer).root,tree.id).type,'Border');assert.equal(doc.root.children.length,0);});
test('motion base resolves Auto dimensions without mutating author values',()=>{const doc=createDocument(element('Border',{Width:'Auto'})),renderer=rendererFor(doc);renderer.elements.get(doc.root.id).getBoundingClientRect=()=>({width:150,height:80});const base=motionBase(renderer);assert.equal(base.root.props.Width,'150');assert.equal(doc.root.props.Width,'Auto');});
test('motion frames restore CSS and text and never commit animated properties',()=>{const child=element('TextBlock',{Text:'Before',Opacity:'1','Canvas.Left':'2'}),doc=createDocument(element('Canvas',{},[child])),renderer=rendererFor(doc),el=renderer.elements.get(child.id);el.style.opacity='1';el.style.left='2px';const baseline=captureMotion(renderer),before=JSON.stringify(doc);patchMotion(renderer,doc,new Map([[child.id,{Text:'During',Opacity:'.3','Canvas.Left':40}]]),baseline);assert.equal(el.textContent,'During');assert.equal(el.style.opacity,'0.3');assert.equal(el.style.left,'40px');restoreMotion(renderer,baseline);assert.equal(el.textContent,'Before');assert.equal(el.style.opacity,'1');assert.equal(el.style.left,'2px');assert.equal(JSON.stringify(doc),before);});
