/** Deterministic authored-XAML animation clocks and keyframe evaluation. */
import {element,find,walk,parentOf,localName} from './model.js';
import {namedTarget,ensureName,readPropertyPath,writePropertyPath,ensureTransformPath,TRANSFORM_PATHS} from './property-path.js';

export const ANIMATION_PROPERTIES=Object.freeze(['Opacity','Width','Height','Canvas.Left','Canvas.Top','Margin','Padding','FontSize','(Panel.Background).(SolidColorBrush.Color)','(Shape.Fill).(SolidColorBrush.Color)',...Object.values(TRANSFORM_PATHS)]);
export const EASINGS=Object.freeze(['Linear','Quadratic','Cubic','Quartic','Quintic','Sine','Circle','Power','Exponential','Back','Bounce','Elastic']);
const number=v=>{const n=Number(v);if(!Number.isFinite(n))throw Error(`Expected a finite animation value, received ${v}.`);return n;};
const same=(a,b)=>Math.abs(a-b)<1e-9;
export function parseTime(value,fallback=0){if(value===null||value===undefined||String(value).trim()==='')return fallback;if(typeof value==='number')return Number.isFinite(value)?value:fallback;const s=String(value).trim();if(/^Forever$/i.test(s))return Infinity;if(/^(Automatic|Auto)$/i.test(s))return fallback;if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s))return Number(s);const m=/^(-)?(?:(\d+)\.)?(\d+):(\d{1,2}):(\d{1,2}(?:\.\d+)?)$/.exec(s);if(!m||Number(m[4])>=60||Number(m[5])>=60)return fallback;return (m[1]?-1:1)*((Number(m[2]||0)*24+Number(m[3]))*3600+Number(m[4])*60+Number(m[5]));}
export function formatTime(seconds){if(!Number.isFinite(Number(seconds)))return 'Forever';const milliseconds=Math.round(Math.max(0,Number(seconds))*1000),hours=Math.floor(milliseconds/3600000),minutes=Math.floor(milliseconds/60000)%60,rest=(milliseconds%60000)/1000;return `${hours}:${String(minutes).padStart(2,'0')}:${rest.toFixed(3).padStart(6,'0').replace(/\.000$/,'').replace(/(\.\d*?)0+$/,'$1')}`;}
export function splineProgress(progress,spline='0.25,0.1,0.25,1'){const p=Array.isArray(spline)?spline:String(spline).split(/[ ,]+/).map(Number);if(p.length!==4||p.some(v=>!Number.isFinite(v))||p.some(v=>v<0||v>1))throw Error('KeySpline requires four numbers with X coordinates between 0 and 1.');const x=Math.min(1,Math.max(0,progress));const cubic=(t,a,b)=>3*(1-t)*(1-t)*t*a+3*(1-t)*t*t*b+t*t*t;let lo=0,hi=1;for(let i=0;i<32;i++){const m=(lo+hi)/2;if(cubic(m,p[0],p[2])<x)lo=m;else hi=m;}return cubic((lo+hi)/2,p[1],p[3]);}
function bounceIn(t,bounces=3,bounciness=2){const b=Math.max(0,Math.floor(Number(bounces)||0));let q=Math.max(1.001,Number(bounciness)||2);if(!b)return t*t;const pow=Math.pow(q,b),oneMinus=1-q,sum=(1-pow)/oneMinus+pow/2,unit=t*sum,start=Math.floor(Math.log(-unit*oneMinus+1)/Math.log(q)),a=(1-Math.pow(q,start))/oneMinus,z=(1-Math.pow(q,start+1))/oneMinus,mid=(a+z)/2,radius=(z-a)/2,amplitude=Math.pow(1/q,b-start);return -amplitude/(radius*radius)*(unit-mid-radius)*(unit-mid+radius);}
export function ease(progress,name='Linear',mode='EaseInOut',options={}){if(typeof name==='object'){options=name.props||name;name=localName(name.type||options.type||'Linear').replace(/Ease$/,'');mode=options.EasingMode||mode;}name=String(name).replace(/Ease$/,'');const t=Math.min(1,Math.max(0,progress));const fn=x=>{switch(name){case 'Quadratic':return x*x;case 'Cubic':return x*x*x;case 'Quartic':return x**4;case 'Quintic':return x**5;case 'Sine':return 1-Math.cos(x*Math.PI/2);case 'Circle':return 1-Math.sqrt(Math.max(0,1-x*x));case 'Power':return x**Math.max(0,Number(options.Power??2));case 'Exponential':{const p=Number(options.Exponent??2);return Math.abs(p)<1e-9?x:(Math.exp(p*x)-1)/(Math.exp(p)-1);}case 'Back':return x*x*x-x*Math.sin(Math.PI*x)*Math.max(0,Number(options.Amplitude??1));case 'Bounce':return bounceIn(x,options.Bounces??3,options.Bounciness??2);case 'Elastic':{const spring=Math.max(0,Number(options.Springiness??3)),osc=Math.max(0,Number(options.Oscillations??3)),expo=spring===0?x:(Math.exp(spring*x)-1)/(Math.exp(spring)-1);return expo*Math.sin((2*Math.PI*osc+Math.PI/2)*x);}default:return x;}};if(mode==='EaseOut')return 1-fn(1-t);if(mode==='EaseInOut')return t<.5?fn(t*2)/2:1-fn((1-t)*2)/2;return fn(t);}
const colors={transparent:'#00000000',black:'#FF000000',white:'#FFFFFFFF',red:'#FFFF0000',green:'#FF008000',blue:'#FF0000FF',yellow:'#FFFFFF00',orange:'#FFFFA500',purple:'#FF800080',gray:'#FF808080',grey:'#FF808080',silver:'#FFC0C0C0',navy:'#FF000080',teal:'#FF008080',lime:'#FF00FF00',aqua:'#FF00FFFF',fuchsia:'#FFFF00FF',pink:'#FFFFC0CB',gold:'#FFFFD700',cornflowerblue:'#FF6495ED',rebeccapurple:'#FF663399'};
export function colorChannels(value){let s=String(value).trim();s=colors[s.toLowerCase()]||s;if(/^#[0-9a-f]{3}$/i.test(s))s='#FF'+[...s.slice(1)].map(c=>c+c).join('');else if(/^#[0-9a-f]{4}$/i.test(s))s='#'+[...s.slice(1)].map(c=>c+c).join('');else if(/^#[0-9a-f]{6}$/i.test(s))s='#FF'+s.slice(1);if(!/^#[0-9a-f]{8}$/i.test(s))throw Error(`Unsupported animation color: ${value}`);return [1,3,5,7].map(i=>parseInt(s.slice(i,i+2),16));}
function unbox(value){const s=String(value);const m=/^\{x:Static\s+(?:[\w:]+\.)?([\w]+)\}$/.exec(s);return m?m[1]:s;}
function tuple(value,type){if(type==='Color')return colorChannels(value);if(type==='Double')return [number(value)];if(type==='Thickness'){const v=String(value).split(/[ ,]+/).filter(Boolean).map(number);if(v.length===1)return Array(4).fill(v[0]);if(v.length===2)return [v[0],v[1],v[0],v[1]];if(v.length===4)return v;throw Error('Thickness needs 1, 2 or 4 numbers.');}if(type==='Point'){const v=String(value).split(/[ ,]+/).filter(Boolean).map(number);if(v.length!==2)throw Error('Point needs two numbers.');return v;}return [unbox(value)];}
function serialized(v,type){if(type==='Color')return '#'+v.map(x=>Math.round(Math.min(255,Math.max(0,x))).toString(16).padStart(2,'0')).join('').toUpperCase();return v.map(x=>typeof x==='number'?String(Math.round(x*1e6)/1e6):x).join(type==='Double'?'':',');}
export function interpolate(a,b,progress,type='Double'){if(['Double','Color','Thickness','Point','Object','Boolean'].includes(a)&&arguments.length===4){const t=a;a=b;b=progress;progress=type;type=t;}if(type==='Object'||type==='Boolean')return unbox(progress<1?a:b);const av=tuple(a,type),bv=tuple(b,type);if(av.length!==bv.length)throw Error('Animation values have incompatible dimensions.');return serialized(av.map((n,i)=>n+(bv[i]-n)*progress),type);}
export function valueType(property,value){if(/(?:^|\.)(?:IsEnabled|IsChecked|IsVisible)\)?$/.test(property)||typeof value==='boolean'||/^(True|False)$/i.test(String(value)))return 'Boolean';if(/Color\)?$/.test(property)||['Background','Foreground','Fill','Stroke','BorderBrush'].includes(property)||/^#/.test(String(value)))return 'Color';if(/(?:Margin|Padding)\)?$/.test(property))return 'Thickness';if(/(?:Origin|Center|Point)\)?$/.test(property))return 'Point';return Number.isFinite(Number(value))&&String(value).trim()!==''?'Double':'Object';}
export function animationChildren(node){return (node?.children||[]).flatMap(c=>{if(c.kind!=='element')return [];const name=localName(c.type);if(name.endsWith('.Children'))return animationChildren(c);return /Animation(?:UsingKeyFrames)?$/.test(name)||name==='Storyboard'||name==='ParallelTimeline'?[c]:[];});}
function keyNodes(track){return (track.children||[]).flatMap(c=>c.kind!=='element'?[]:localName(c.type).endsWith('.KeyFrames')?keyNodes(c):/KeyFrame$/.test(localName(c.type))?[c]:[]);}
function trackType(track){return localName(track.type).replace(/Animation(?:UsingKeyFrames)?$/,'');}
function distance(a,b,type){try{const av=tuple(a,type),bv=tuple(b,type);return Math.sqrt(av.reduce((s,x,i)=>s+(Number(x)-Number(bv[i]))**2,0));}catch{return 0;}}
export function keyframes(track,duration=simpleDuration(track)){
  const frames=keyNodes(track).map((node,index)=>{const raw=String(node.props.KeyTime??'Uniform'),explicit=!/^(Uniform|Paced)$/i.test(raw);let time=explicit?(raw.endsWith('%')?Number(raw.slice(0,-1))*duration/100:parseTime(raw,NaN)):NaN;if(!Number.isFinite(time))time=NaN;const mode=localName(node.type).replace(/(?:Double|Color|Thickness|Point|Object|Boolean)KeyFrame$/,'');return {id:node.id,node,index,time,value:node.props.Value??(function text(n){return n.text??(n.children||[]).map(text).join('');})(node),mode,kind:mode,raw,paced:/^Paced$/i.test(raw)};});
  const end=Number.isFinite(duration)?Math.max(0,duration):1;let anchor=-1,anchorTime=0;
  for(let i=0;i<=frames.length;i++){if(i<frames.length&&!Number.isFinite(frames[i].time))continue;const right=i<frames.length?Math.max(0,frames[i].time):end,count=i-anchor-(i===frames.length?1:0);for(let j=anchor+1;j<i;j++)frames[j].time=anchorTime+(right-anchorTime)*(j-anchor)/Math.max(1,count+(i<frames.length?0:0));if(i<frames.length){anchor=i;anchorTime=frames[i].time;}}
  // Paced spans use Euclidean distances between values, not uniform spacing.
  for(let i=0;i<frames.length;){if(!frames[i].paced){i++;continue;}const start=i;while(i<frames.length&&frames[i].paced)i++;const stop=i,left=start>0?start-1:start,right=stop<frames.length?stop:stop-1,a=start>0?frames[left].time:0,b=stop<frames.length?frames[right].time:end;const distances=[];let total=0;for(let k=left+1;k<=right;k++){const d=distance(frames[k-1].value,frames[k].value,trackType(track));distances.push(d);total+=d;}if(start===0)frames[0].time=0;let passed=0;for(let k=left+1;k<=right;k++){passed+=distances[k-left-1];if(frames[k].paced)frames[k].time=a+(b-a)*(total>0?passed/total:(k-left)/Math.max(1,right-left));}}
  return frames.sort((a,b)=>a.time-b.time||a.index-b.index);
}
function repeatDuration(node,duration){const s=String(node.props?.RepeatBehavior??'1x').trim(),cycle=duration*(String(node.props?.AutoReverse).toLowerCase()==='true'?2:1);if(/^Forever$/i.test(s))return cycle===0?0:Infinity;const m=/^([+]?(?:\d+(?:\.\d*)?|\.\d+))x$/i.exec(s);if(m)return Number(m[1])===0?0:cycle*Number(m[1]);return Math.max(0,parseTime(s,cycle));}
export function simpleDuration(node){const explicit=parseTime(node.props?.Duration,NaN);if(!Number.isNaN(explicit))return Math.max(0,explicit);const children=animationChildren(node);if(children.length)return Math.max(0,...children.map(c=>{const speed=Number(c.props.SpeedRatio??1);return Math.max(0,parseTime(c.props.BeginTime,0))+activeDuration(c)/Math.max(Number.EPSILON,speed);}));const keys=keyNodes(node);if(keys.length){const times=keys.map(k=>parseTime(k.props.KeyTime,NaN)).filter(Number.isFinite);return Math.max(0,times.length?Math.max(...times):1);}return /Animation/.test(localName(node.type))?1:0;}
export function activeDuration(node,duration=simpleDuration(node)){return repeatDuration(node,duration);}
export function clockTime(node,parentTime,duration=simpleDuration(node)){
  if(/^\{x:Null\}$|^null$/i.test(String(node.props?.BeginTime)))return null;const start=parseTime(node.props?.BeginTime,0),speed=Number(node.props?.SpeedRatio??1);if(!(speed>0)||!Number.isFinite(speed))return null;const elapsed=(parentTime-start)*speed;if(elapsed<0)return null;const active=activeDuration(node,duration),reverse=String(node.props?.AutoReverse).toLowerCase()==='true';if(/^0(?:\.0+)?x$/i.test(String(node.props?.RepeatBehavior??''))||active===0&&duration>0)return null;
  if(duration===0)return String(node.props?.FillBehavior)==='Stop'?null:0;
  if(elapsed>=active&&String(node.props?.FillBehavior)==='Stop')return null;
  const ended=elapsed>=active,local=ended?active:elapsed;if(!Number.isFinite(duration))return Math.max(0,local);const cycle=duration*(reverse?2:1);let phase=local%cycle;if(ended&&local>0&&same(phase,0))phase=cycle;return reverse&&phase>duration?cycle-phase:Math.min(duration,phase);
}
function easingNode(node){return (node.children||[]).flatMap(c=>c.kind==='element'&&localName(c.type).endsWith('.EasingFunction')?(c.children||[]):[c]).find(c=>c.kind==='element'&&/Ease$/.test(localName(c.type)));}
export function sampleTrack(track,time,base,duration=simpleDuration(track)){
  const type=trackType(track);if(!['Double','Color','Thickness','Point','Object','Boolean'].includes(type))throw Error(`${type} animation preview is not supported.`);const frames=keyframes(track,duration);
  if(frames.length){let prior={time:0,value:base};for(const frame of frames){if(time>=frame.time){prior=frame;continue;}const span=frame.time-prior.time,p=span<=0?1:Math.min(1,Math.max(0,(time-prior.time)/span));if(frame.mode==='Discrete'||type==='Object'||type==='Boolean')return unbox(prior.value);let progress=p;if(frame.mode==='Spline')progress=splineProgress(p,frame.node.props.KeySpline);if(frame.mode==='Easing')progress=ease(p,easingNode(frame.node)||'Linear');return interpolate(prior.value,frame.value,progress,type);}return unbox(prior.value);}
  const from=track.props.From,to=track.props.To,by=track.props.By;let a=from??base,b=to??base;if(to===undefined&&by!==undefined){const av=tuple(a,type),bv=tuple(by,type);b=serialized(av.map((x,i)=>Number(x)+Number(bv[i])),type);}const p=duration===0?1:Math.min(1,Math.max(0,time/duration));return interpolate(a,b,ease(p,easingNode(track)||'Linear'),type);
}
export function listStoryboards(doc){const result=[];walk(doc.root,n=>{if(n.kind==='element'&&localName(n.type)==='Storyboard'){const parent=parentOf(doc.root,n.id);result.push({id:n.id,node:n,name:n.props['x:Key']||n.props['x:Name']||n.props.Name||parent?.props?.['x:Name']||parent?.props?.Name||'Storyboard',duration:simpleDuration(n)});}});return result;}
export function storyboardTracks(doc,story,{targetId=null,nameScopeId=null}={}){if(!nameScopeId){let scope=parentOf(doc.root,story.id);while(scope&&!['ControlTemplate','DataTemplate'].includes(localName(scope.type)))scope=parentOf(doc.root,scope.id);nameScopeId=scope?.id||null;}const list=[];const inspect=(node,inheritedName='',inheritedProperty='')=>{const targetName=node.props['Storyboard.TargetName']??node.props.TargetName??inheritedName,property=node.props['Storyboard.TargetProperty']??node.props.TargetProperty??inheritedProperty,children=animationChildren(node);if(/Animation(?:UsingKeyFrames)?$/.test(localName(node.type))){const target=targetName?namedTarget(doc,targetName,nameScopeId):find(doc.root,targetId||nameScopeId||doc.root.id);list.push({id:node.id,node,targetId:target?.id||null,targetName,property,type:trackType(node),duration:simpleDuration(node),frames:keyframes(node)});}for(const child of children)inspect(child,targetName,property);};inspect(story);return list;}
export function sampleStoryboard(doc,story,time,{baseDocument=doc,targetId=null,nameScopeId=null}={}){
  if(!nameScopeId){let scope=parentOf(doc.root,story.id);while(scope&&!['ControlTemplate','DataTemplate'].includes(localName(scope.type)))scope=parentOf(doc.root,scope.id);nameScopeId=scope?.id||null;}
  const overrides=new Map(),warnings=[];const inspect=(node,parentTime,inheritedName='',inheritedProperty='')=>{const local=clockTime(node,parentTime);if(local===null)return;const targetName=node.props['Storyboard.TargetName']??node.props.TargetName??inheritedName,property=node.props['Storyboard.TargetProperty']??node.props.TargetProperty??inheritedProperty;if(/Animation(?:UsingKeyFrames)?$/.test(localName(node.type))){const target=targetName?namedTarget(doc,targetName,nameScopeId):find(doc.root,targetId||nameScopeId||doc.root.id);if(!target){warnings.push(`Animation target ${targetName||targetId||'(implicit)'} is missing or ambiguous.`);return;}if(!property){warnings.push('Animation has no target property.');return;}try{const baseNode=find(baseDocument.root,target.id)||target,base=readPropertyPath(baseDocument,baseNode,property),value=sampleTrack(node,local,base);overrides.set(target.id,{...(overrides.get(target.id)||{}),[property]:value});}catch(error){warnings.push(error.message);}}else for(const child of animationChildren(node))inspect(child,local,targetName,property);};inspect(story,Math.max(0,Number(time)||0));return {overrides,values:overrides,warnings};
}
export function applyAnimationValues(doc,values){const map=values instanceof Map?values:values?.overrides||values?.values;if(!(map instanceof Map))throw Error('Animation values must be a Map.');for(const [id,props] of map){const node=find(doc.root,id);if(node)for(const [path,value] of Object.entries(props))writePropertyPath(doc,node,path,value);}return doc;}
export function resourcesFor(doc,owner=doc.root){if(localName(owner.type)==='ResourceDictionary')return owner;let resources=owner.children.find(c=>c.kind==='element'&&localName(c.type).endsWith('.Resources'));if(!resources){resources=element(`${localName(owner.type)}.Resources`);owner.children.unshift(resources);}const dictionary=resources.children.find(c=>c.kind==='element'&&localName(c.type)==='ResourceDictionary');return dictionary||resources;}
export function createStoryboard(doc,name='Animation',duration=2){if(doc.framework!=='WPF')throw Error('This timeline authors WPF Storyboards. A native animation adapter is required for the selected framework.');const used=new Set(listStoryboards(doc).map(x=>x.name));const stem=String(name).trim()||'Animation';let key=stem,i=2;while(used.has(key))key=stem+i++;const story=element('Storyboard',{'x:Key':key,Duration:formatTime(duration)});doc.root.props['xmlns:x']??='http://schemas.microsoft.com/winfx/2006/xaml';resourcesFor(doc).children.push(story);return story;}
export function addTrack(doc,story,target,property,explicitType){if(typeof target==='string')target=find(doc.root,target);if(!target)throw Error('Select an animation target.');if(['Background','Foreground','Fill','Stroke','BorderBrush'].includes(property))property=`(${target.type}.${property}).(SolidColorBrush.Color)`;else property=property.replace(/^\((?:Panel|Control)\.(Background|Foreground|BorderBrush)\)/,(_,key)=>`(${target.type}.${key})`);property=ensureTransformPath(doc,target,property);const name=ensureName(doc,target),existing=storyboardTracks(doc,story).find(t=>t.targetId===target.id&&t.property===property);if(existing)return existing.node;const type=explicitType||valueType(property,readPropertyPath(doc,target,property));const track=element(`${type}AnimationUsingKeyFrames`,{'Storyboard.TargetName':name,'Storyboard.TargetProperty':property,...(story.props.Duration?{Duration:formatTime(simpleDuration(story))}:{})});story.children.push(track);return track;}
function enumValue(type,property,value){if(type==='Boolean'){if(!/^(true|false)$/i.test(String(value)))throw Error('Boolean keyframes require True or False.');return /^true$/i.test(String(value))?'True':'False';}if(type==='Object'&&/(?:^|\.)Visibility\)?$/.test(property)&&/^(Visible|Hidden|Collapsed)$/.test(String(value)))return `{x:Static Visibility.${value}}`;return String(value);}
export function setKeyframe(track,time,value,{interpolation='Linear',mode=interpolation,easing='Cubic',easingMode='EaseInOut',spline='0.25,0.1,0.25,1'}={}){
  if(['EaseIn','EaseOut','EaseInOut'].includes(mode)){easingMode=mode;mode=interpolation;}if(mode==='Easing'&&String(easing).replace(/Ease$/,'')==='Linear')mode='Linear';
  const type=trackType(track),property=track.props['Storyboard.TargetProperty']||track.props.TargetProperty||'';value=enumValue(type,property,value);if(!['Object','Boolean'].includes(type))tuple(value,type);if(!Number.isFinite(Number(time))||Number(time)<0)throw Error('Keyframe time must be nonnegative and finite.');
  if(!/UsingKeyFrames$/.test(localName(track.type))){if(track.props.By!==undefined&&track.props.From===undefined&&track.props.To===undefined)throw Error('Resolve the base value before converting a By-only animation to keyframes.');const oldType=trackType(track),oldFrom=track.props.From,oldTo=track.props.To,oldBy=track.props.By,oldDuration=simpleDuration(track);track.type=track.type.replace(/Animation$/,'AnimationUsingKeyFrames');track.children=track.children.filter(n=>n.kind!=='element'||!localName(n.type).endsWith('.EasingFunction'));delete track.props.From;delete track.props.To;delete track.props.By;if(oldFrom!==undefined)setKeyframe(track,0,oldFrom,{interpolation:'Linear'});if(oldTo!==undefined)setKeyframe(track,oldDuration,oldTo,{interpolation:'Linear'});else if(oldFrom!==undefined&&oldBy!==undefined){const a=tuple(oldFrom,oldType),b=tuple(oldBy,oldType);setKeyframe(track,oldDuration,serialized(a.map((v,i)=>Number(v)+Number(b[i])),oldType),{interpolation:'Linear'});}}
  if(['Object','Boolean'].includes(type))mode='Discrete';if(!['Linear','Discrete','Spline','Easing'].includes(mode))throw Error('Unknown keyframe interpolation.');if(mode==='Spline')splineProgress(.5,spline);const existing=keyframes(track).find(k=>same(k.time,Number(time))),node=existing?.node||element(`${mode}${type}KeyFrame`);node.type=`${mode}${type}KeyFrame`;node.props.KeyTime=formatTime(Number(time));node.props.Value=value;node.children=node.children.filter(n=>!n.type?.endsWith('.Value'));delete node.props.KeySpline;node.children=node.children.filter(n=>n.kind!=='element'||!localName(n.type).endsWith('.EasingFunction'));if(mode==='Spline')node.props.KeySpline=Array.isArray(spline)?spline.join(','):String(spline);if(mode==='Easing')node.children.push(element(`${mode}${type}KeyFrame.EasingFunction`,{},[element(`${String(easing).replace(/Ease$/,'')}Ease`,{EasingMode:easingMode})]));if(!existing){let wrapper=track.children.find(n=>n.kind==='element'&&localName(n.type).endsWith('.KeyFrames'));(wrapper||track).children.push(node);}return node;
}
export class AnimationPlayer extends EventTarget {
  constructor({duration=3,rate=1,loop=false,now=()=>performance.now(),schedule=callback=>requestAnimationFrame(callback),cancel=id=>cancelAnimationFrame(id)}={}){super();this.duration=duration;this.rate=rate;this.loop=loop;this.time=0;this.playing=false;this.now=now;this.schedule=schedule;this.cancel=cancel;this.frameId=null;this.last=null;this.tick=this.tick.bind(this);}
  emit(type){const event=new Event(type);Object.defineProperty(event,'detail',{value:{time:this.time}});this.dispatchEvent(event);}
  seek(time){this.time=Math.max(0,Math.min(Number.isFinite(this.duration)?this.duration:Infinity,Number(time)||0));this.last=this.now();this.emit('frame');return this.time;}
  play(){if(this.playing)return;if(Number.isFinite(this.duration)&&this.time>=this.duration)this.time=0;this.playing=true;this.last=this.now();this.emit('play');this.emit('frame');this.frameId=this.schedule(this.tick);}
  tick(){if(!this.playing)return;const now=this.now(),delta=Math.max(0,(now-this.last)/1000);this.last=now;this.time+=delta*Math.max(0,Number(this.rate)||0);const duration=Math.max(0,Number(this.duration));if(Number.isFinite(duration)&&this.time>=duration){if(this.loop&&duration>0)this.time%=duration;else{this.time=duration;this.playing=false;this.frameId=null;this.emit('frame');this.emit('ended');return;}}this.emit('frame');this.frameId=this.schedule(this.tick);}
  pause(){if(this.frameId!==null)this.cancel(this.frameId);this.frameId=null;this.playing=false;this.last=null;this.emit('pause');}
  stop(){this.pause();this.time=0;this.emit('frame');this.emit('stop');}
}
