/** Isolated preview documents and reversible DOM updates for animation/state playback. */
import {clone,find,isElement,isProperty,localName,parentOf,walk} from './model.js';
import {applyAnimationValues} from './animation.js';
import {applyAppearance,brushNode,brushCSS} from './appearance.js';
import {resolveStyle} from './styling.js';

export function motionDocument(renderer){const doc=clone(renderer.document),templates=renderer.runtimeTemplates instanceof Map?[...renderer.runtimeTemplates.values()]:renderer.runtimeTemplates||[];for(const entry of templates){const owner=find(doc.root,entry.ownerId),tree=entry.tree;if(owner&&tree&&!find(doc.root,tree.id))owner.children.push(clone(tree));}return doc;}
function effectiveFor(renderer,doc,node,inputs){const context=renderer.contextFor?.(node)||renderer.sampleData||{};const result=resolveStyle(doc,node,{context,root:renderer.sampleData||context,transient:inputs instanceof Map?inputs.get(node.id)||{}:renderer.transient||{},resolveSource:renderer.resourceResolver});return result;}
/** Capture style/base values before applying any frame, including measured Auto sizes. */
export function motionBase(renderer,doc=motionDocument(renderer)){const result=clone(doc);walk(result.root,node=>{if(!isElement(node))return;const effective=effectiveFor(renderer,result,node);node.props=effective.properties;node.children=effective.node.children;for(const [property,value] of Object.entries(node.props)){if(typeof value==='string'&&value.startsWith('{')&&renderer.value){const resolved=renderer.value(value,null,node);if(resolved!==undefined&&typeof resolved!=='object')node.props[property]=resolved;}}const el=renderer.elements.get(node.id);if(el){const rect=el.getBoundingClientRect?.();for(const [property,dimension] of [['Width','width'],['Height','height']])if(node.props[property]===undefined||node.props[property]==='Auto'){const layoutSize=el[property==='Width'?'offsetWidth':'offsetHeight'];const measured=Number.isFinite(layoutSize)&&layoutSize>0?layoutSize:rect?.[dimension];if(Number.isFinite(measured))node.props[property]=String(measured);}}});return result;}
function styleSnapshot(style){const result={};if(style&&typeof style.length==='number'&&style.getPropertyValue){for(let i=0;i<style.length;i++){const name=style[i];result[name]=style.getPropertyValue(name);}}else for(const key of Object.keys(style||{}))if(key!=='cssText')result[key]=style[key];return result;}
export function captureMotion(renderer){const baselines=new Map();for(const [id,el] of renderer.elements){baselines.set(id,{css:el.style.cssText||'',style:styleSnapshot(el.style),text:el.textContent,children:[...(el.childNodes||el.children||[])],disabled:el.disabled,value:el.value,checked:el.checked,visibleDisplay:el._visibleDisplay,controls:[...(el.querySelectorAll?.('input,button,select,textarea')||[])].map(input=>({input,value:input.value,checked:input.checked,disabled:input.disabled})),textChanged:false});}return baselines;}
export function restoreMotion(renderer,baselines,{inputs=true}={}){if(!baselines)return;for(const [id,baseline] of baselines){const el=renderer.elements.get(id);if(!el)continue;el.style.cssText=baseline.css;if(typeof el.style.length!=='number'){for(const key of Object.keys(el.style))if(key!=='cssText')delete el.style[key];Object.assign(el.style,baseline.style);}el._visibleDisplay=baseline.visibleDisplay;if(baseline.textChanged){el.replaceChildren(...baseline.children);if(!baseline.children.length)el.textContent=baseline.text;baseline.textChanged=false;}if(baseline.disabled!==undefined)el.disabled=baseline.disabled;if(inputs&&baseline.value!==undefined)el.value=baseline.value;if(inputs&&baseline.checked!==undefined)el.checked=baseline.checked;for(const saved of baseline.controls||[]){if(saved.disabled!==undefined)saved.input.disabled=saved.disabled;if(inputs&&saved.value!==undefined)saved.input.value=saved.value;if(inputs&&saved.checked!==undefined)saved.input.checked=saved.checked;}}}
function ownerFor(renderer,doc,node){const ownerId=renderer.templateOwners instanceof Map?renderer.templateOwners.get(node.id):renderer.templateOwners?.[node.id];const owner=typeof ownerId==='object'?ownerId:ownerId&&find(doc.root,ownerId);if(owner)return owner;let ancestor=parentOf(doc.root,node.id);while(ancestor){if(ancestor.props?.__templateOwner)return find(doc.root,ancestor.props.__templateOwner);ancestor=parentOf(doc.root,ancestor.id);}return null;}
function propertiesFor(renderer,doc,node,owner,inputs){const {node:effective,properties}=effectiveFor(renderer,doc,node,inputs),ownerProps=owner?effectiveFor(renderer,doc,owner,inputs).properties:null;for(const [key,value] of Object.entries(properties)){const templated=String(value).match(/^\{TemplateBinding\s+([^,}]+)/);if(templated&&ownerProps)properties[key]=ownerProps[templated[1]]??'';else if(typeof value==='string'&&value.startsWith('{')&&renderer.value){const resolved=renderer.value(value,ownerProps,node);if(resolved!==undefined&&typeof resolved!=='object')properties[key]=resolved;}}effective.props={...properties};return effective;}
function updatePath(el,node,doc){if(localName(node.type)!=='Path')return;const path=el.tagName?.toLowerCase()==='path'?el:el.querySelector?.('path');if(!path)return;path.setAttribute('d',String(node.props.Data||'').replace(/^\s*F[01]\s*/i,''));path.setAttribute('fill-rule',/^\s*F1/i.test(String(node.props.Data||''))?'nonzero':'evenodd');for(const [property,attribute] of [['Fill','fill'],['Stroke','stroke']]){const brush=brushNode(doc,node,property),value=brush?brushCSS(brush):node.props[property];if(value&&!String(value).includes('gradient('))path.setAttribute(attribute,value);}
  if(node.props.StrokeThickness!==undefined)path.setAttribute('stroke-width',node.props.StrokeThickness);
}
/** `overrides` is Map<nodeId, Record<propertyPath,value>>; authoring source is never modified. */
export function patchMotion(renderer,doc,overrides,baselines,{inputs=new Map()}={}){restoreMotion(renderer,baselines,{inputs:false});const frame=clone(doc);applyAnimationValues(frame,overrides||new Map());for(const [id,el] of renderer.elements){const raw=find(frame.root,id);if(!raw)continue;const node=propertiesFor(renderer,frame,raw,ownerFor(renderer,frame,raw),inputs),p=node.props;applyAppearance(el,node,frame,p);const parent=parentOf(frame.root,id);if(parent&&localName(parent.type)==='Canvas'){for(const [property,css] of [['Canvas.Left','left'],['Canvas.Top','top'],['Canvas.Right','right'],['Canvas.Bottom','bottom']])if(p[property]!==undefined&&Number.isFinite(Number(p[property])))el.style[css]=Number(p[property])+'px';if(p['Canvas.Left']!==undefined&&p['Canvas.Right']!==undefined)el.style.right='auto';if(p['Canvas.Top']!==undefined&&p['Canvas.Bottom']!==undefined)el.style.bottom='auto';}
    const type=localName(node.type),text=type==='TextBlock'?p.Text:['Label','ContentPresenter','Button','ToggleButton'].includes(type)?p.Content:undefined;if(text!==undefined&&(!node.children.some(c=>isElement(c)&&!isProperty(c))||type==='TextBlock')){if(el.textContent!==String(text)){const baseline=baselines?.get(id);if(baseline)baseline.textChanged=true;el.textContent=String(text);}}
    if(p.IsEnabled!==undefined){let disabled=String(p.IsEnabled).toLowerCase()==='false',ancestor=parentOf(frame.root,id);while(ancestor&&!disabled){disabled=String(propertiesFor(renderer,frame,ancestor,ownerFor(renderer,frame,ancestor),inputs).props.IsEnabled).toLowerCase()==='false';ancestor=parentOf(frame.root,ancestor.id);}if('disabled' in el)el.disabled=disabled;el.querySelectorAll?.('input,button,select,textarea').forEach(child=>child.disabled=disabled);}
    if(overrides?.has(id)){const changed=overrides.get(id);if(['TextBox','PasswordBox'].includes(type)&&changed.Text!==undefined&&p.Text!==undefined)el.value=String(p.Text);if(type==='NumericUpDown'&&changed.Value!==undefined&&p.Value!==undefined)el.value=String(p.Value);if(['CheckBox','RadioButton'].includes(type)&&changed.IsChecked!==undefined&&p.IsChecked!==undefined){const input=el.querySelector?.('input');if(input)input.checked=String(p.IsChecked).toLowerCase()==='true';}}
    updatePath(el,node,frame);
  }return frame;
}
